server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/material?useUnicode=true&characterEncoding=UTF-8&serverTimeZone=UTC
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver

  task:
    scheduling:
      thread-name-prefix: apple
      pool:
        size: 4
      shutdown:
        await-termination: true
        await-termination-period: 60

back:
  username: root
  password: abc123
  host: localhost
  databasename: book
  mysqlbin: D:/MySQL/MySQL Server 8.0/bin
  savepath: D:/TestModel